# Generated by Django 6.1.1 on 2026-10-04 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('bachelor', "Bachelor's"), ('master', "Master's")], default='bachelor', max_length=10)),
                ('current_semester', models.PositiveSmallIntegerField(default=1)),
                ('start_term', models.CharField(choices=[('spring', 'Spring'), ('fall', 'Fall')], default='spring', max_length=6)),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('required_credits', models.PositiveSmallIntegerField(default=120)),
                ('target_cgpa', models.FloatField(default=4.3)),
                ('onboarded', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('courses', models.JSONField(blank=True, default=list)),
                ('summary_credits', models.FloatField(blank=True, null=True)),
                ('summary_gpa', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('user', 'number')},
            },
        ),
    ]
